In [20]:
"""
class 14. Classification Regularization & Overfitting-Underfitting-Generalization 

Objectives:
1. ML Algorithm Classification
2. ML Workflow
3. Polynomial Regression
4. Choice of Hyperparameters
5. Model Evaluation 
6. Understand the problem of overfitting
7. Regularization to solve overfitting
"""

import numpy as np
import pandas as pd

In [21]:
DATASET_PATH = "E:\\PyCharmProjects\\pythonProject\\data\\housing.csv"

In [22]:
housing_dataset = pd.read_csv(DATASET_PATH)
housing_dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [23]:
""" Feature Engineering
"""

housing_dataset = housing_dataset[['area', 'price']]
housing_dataset.head()

   area     price
0  7420  13300000
1  8960  12250000
2  9960  12250000
3  7500  12215000
4  7420  11410000

In [24]:
mean = housing_dataset.mean()
std = housing_dataset.std()
housing_dataset = (housing_dataset - mean) / std
housing_dataset.head()

       area     price
0  1.045766  4.562174
1  1.755397  4.000809
2  2.216196  4.000809
3  1.082630  3.982096
4  1.045766  3.551716

In [25]:
""" ML Algorithm
- Supervised Learning 
  - Regression
  - Classification
- Unsupervised Learning
  - Clustering
- Reinforcement Learning
- Semi-Supervised Learning
"""
print("ML Algorithm Classification")

ML Algorithm Classification

In [26]:
""" ML Checklist
1. Creat a research proposal (one page)
2. Identify the research questions
3. For each research question:
   3.1. Perform Literature Review
   3.2. Comment if the research questions is answered: fully/partially/unanswered
   3.3. Identify literature gaps
   3.4. Design an Experiment (Robust, Reproducible, Rigorous)
   3.5. Result Analysis
"""
print("ML Checklist")

ML Checklist

In [27]:
""" Linear Regression
Single input LR: y_pred = w * x + b
Multiple input LR: y_pred = w1 * x1 + w2 * x2 + ... + wn * xn + b
Polynomial Regression:
  y_pred = ax^2 + bx^1 + cx^0 (degree 2) (a, b, c coefficients) 
  
Why polynomial equation instead of linear equation?
- To recognize non linear pattern
"""
from sklearn.model_selection import train_test_split


X = housing_dataset.drop('price', axis=1).values
y = housing_dataset['price'].values
print(X.shape)
print(y.shape)

X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

(545, 1)
(545,)

In [28]:
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42
)

In [29]:
X_train.shape, X_test.shape, X_val.shape

((327, 1), (109, 1), (109, 1))

In [30]:
def model(x, w1, w2, b):
    y_pred = w1 * x**3 + w2 * x**2 + b
    return y_pred

In [31]:
""" Parameter initialization
"""

w1 = np.random.randint(low=100, high=200)
w2 = np.random.randint(low=100, high=200)
b = np.random.randint(low=100, high=200)

print(w1, w2, b)
y_pred = model(X_train, w1, w2, b)
y_pred

134 196 160

array([[  181.19651401],
       [ 1414.68351627],
       [  213.62577869],
       [  529.17122679],
       [  198.06716353],
       [ 1679.92345282],
       [  179.86215335],
       [  199.44329392],
       [ 1524.60166095],
       [  253.89064421],
       [  205.61541825],
       [  215.87568376],
       [  171.50780128],
       [  160.89844216],
       [ 5109.97158218],
       [  177.90061858],
       [  209.95085938],
       [  160.22581543],
       [  203.93690578],
       [  222.04021617],
       [  220.02197573],
       [  160.49083491],
       [  638.46745338],
       [  167.2488408 ],
       [  162.79340136],
       [  164.54922101],
       [  222.07361103],
       [  226.35117185],
       [  357.57839515],
       [  189.84933638],
       [  201.55163095],
       [  205.21986473],
       [  222.12323814],
       [  211.18138182],
       [  179.97966113],
       [  213.81037013],
       [  163.62081516],
       [  181.19651401],
       [  950.19819033],
       [  219.66821417],
       [  181.19651401],
       [  385.2959899 ],
       [  198.06716353],
       [  221.08316561],
       [  205.61541825],
       [  174.00320651],
       [  190.94993815],
       [  164.9879146 ],
       [  888.23553143],
       [  192.38231256],
       [  858.45609615],
       [  107.57538127],
       [  268.00738073],
       [  221.82651076],
       [  500.8360769 ],
       [  202.15155552],
       [  213.81037013],
       [  174.00320651],
       [  198.15949384],
       [  165.64197259],
       [  184.60696733],
       [  950.19819033],
       [  205.81218966],
       [  165.83437284],
       [ 2161.95416023],
       [  179.97966113],
       [  228.2909111 ],
       [  238.03912771],
       [  201.55163095],
       [  221.28136114],
       [  287.3625635 ],
       [  160.10339047],
       [  215.59517178],
       [  198.06716353],
       [  221.82651076],
       [  188.09170106],
       [22928.54938322],
       [  559.76635678],
       [  297.77496418],
       [  190.72976848],
       [  210.12942601],
       [ 2452.51783034],
       [ 3682.4322086 ],
       [  221.58729924],
       [  215.87568376],
       [  385.2959899 ],
       [  177.49869251],
       [  193.3699705 ],
       [  214.42415668],
       [  196.59768675],
       [  215.87568376],
       [  222.09625808],
       [  202.95866189],
       [  160.97342963],
       [  173.62980015],
       [  210.12942601],
       [  184.84794663],
       [  160.89844216],
       [  287.3625635 ],
       [  174.00320651],
       [  191.65446616],
       [  209.77139308],
       [  192.93050971],
       [  208.73933717],
       [ 9694.76806808],
       [ 1049.29914999],
       [  253.89064421],
       [  214.42415668],
       [  190.72976848],
       [  214.42415668],
       [  214.05808162],
       [  195.73393347],
       [  187.23442587],
       [  209.77139308],
       [  277.44331347],
       [  174.00320651],
       [  169.59781023],
       [  950.19819033],
       [  216.68658067],
       [  193.3699705 ],
       [  195.12289993],
       [  217.20085944],
       [  277.44331347],
       [  234.9001553 ],
       [  182.03996087],
       [  193.3699705 ],
       [  287.3625635 ],
       [  170.42639161],
       [  195.12289993],
       [  218.16341897],
       [ 1488.77890651],
       [  222.07361103],
       [  181.14595249],
       [  201.55163095],
       [  165.64197259],
       [  218.38985038],
       [  173.25967842],
       [  164.54922101],
       [  244.0743154 ],
       [  174.00320651],
       [  189.40940594],
       [  647.76806961],
       [  160.01585487],
       [  162.79340136],
       [  177.90061858],
       [  174.00320651],
       [  332.06940379],
       [  193.11564505],
       [  773.80736658],
       [  165.47390037],
       [  195.55951052],
       [  193.10633851],
       [  162.79340136],
       [  183.32622162],
       [  222.07402088],
       [  552.38150088],
       [  164.54922101],
       [  790.18238737],
       [  275.51777621],
       [  211.18138182],
       [ 2377.46933498],
       [  189.84933638],
       [  221.28136114],
       [  210.48382088],
       [  177.90061858],
       [  215.87568376],
       [ 2026.13271594],
       [ 1524.60166095],
       [  198.06716353],
       [  196.86419137],
       [  214.42415668],
       [  244.0743154 ],
       [  221.22403329],
       [ 1351.5641692 ],
       [  211.18138182],
       [  209.77139308],
       [  489.75042018],
       [  213.62577869],
       [  385.2959899 ],
       [  858.45609615],
       [  170.42639161],
       [  181.14595249],
       [  162.79340136],
       [  193.3699705 ],
       [  160.95752804],
       [  174.00320651],
       [  220.08782866],
       [  221.22403329],
       [  801.25184709],
       [  208.73933717],
       [  695.98650075],
       [  209.32719077],
       [ 3143.05727392],
       [  196.51710579],
       [19663.98816519],
       [  244.0743154 ],
       [  211.18138182],
       [  602.38757727],
       [  205.61541825],
       [  221.28136114],
       [  523.70141757],
       [  200.29172153],
       [  174.00320651],
       [  198.06716353],
       [  215.59517178],
       [  221.84063018],
       [  209.77139308],
       [  527.60319196],
       [  210.12942601],
       [  181.53959264],
       [  275.51777621],
       [  221.58729924],
       [  385.2959899 ],
       [  183.16582491],
       [  214.42415668],
       [  195.12289993],
       [  332.06940379],
       [  190.94993815],
       [  179.53172922],
       [  215.01930034],
       [  179.97966113],
       [  535.48534954],
       [  290.43405547],
       [  203.21075854],
       [  195.12289993],
       [  647.76806961],
       [  221.28136114],
       [  196.43023491],
       [  161.25891203],
       [ 3008.49211884],
       [  222.07361103],
       [  204.42099021],
       [ 2216.8498877 ],
       [  156.4671209 ],
       [  174.00320651],
       [  162.79340136],
       [  204.28536091],
       [  179.97966113],
       [  222.07361103],
       [  162.79340136],
       [  431.83342891],
       [  161.42027849],
       [  287.3625635 ],
       [  163.62081516],
       [  220.36494899],
       [  192.93050971],
       [  222.12203644],
       [  188.09170106],
       [  216.68658067],
       [  165.64197259],
       [  846.76555516],
       [  219.62303024],
       [  221.08316561],
       [  162.40619915],
       [  195.12289993],
       [  264.3661338 ],
       [ 1418.96635113],
       [  535.48534954],
       [ 1524.60166095],
       [  447.67165725],
       [  164.54922101],
       [  264.3661338 ],
       [  214.42415668],
       [  181.19651401],
       [  179.97966113],
       [ 5006.14395739],
       [  160.00001219],
       [  161.56799586],
       [  221.22403329],
       [  177.49869251],
       [  222.07361103],
       [  187.23442587],
       [  275.51777621],
       [  212.19847116],
       [  221.47281224],
       [  165.30424351],
       [  216.68658067],
       [  213.81037013],
       [  190.72976848],
       [  458.19930897],
       [  193.3699705 ],
       [  287.3625635 ],
       [  191.61043775],
       [  287.3625635 ],
       [ 2966.45699386],
       [  209.40980077],
       [  169.36236948],
       [  211.18138182],
       [  160.00875975],
       [  164.54922101],
       [  174.00320651],
       [  216.97973834],
       [ 1030.22950228],
       [  385.2959899 ],
       [  219.37788464],
       [  220.94050593],
       [  160.9938322 ],
       [  253.89064421],
       [  222.07361103],
       [  219.43282319],
       [  211.18138182],
       [  201.96789088],
       [  210.12942601],
       [  198.06716353],
       [  195.12289993],
       [  222.30581136],
       [  179.97966113],
       [  198.06716353],
       [  162.05130922],
       [  242.50115255],
       [  198.06716353],
       [  193.3699705 ],
       [  198.06716353],
       [  165.64197259],
       [  161.42027849],
       [  182.03996087],
       [ 4537.26868698],
       [  222.07361103],
       [  215.01930034],
       [  165.64197259],
       [  468.26251394],
       [ 1524.60166095],
       [  214.11955443],
       [  220.47780126],
       [ 3358.07395072],
       [  177.90061858],
       [  198.06716353]])

In [32]:
def cost_function(x, y_true, w1, w2, b):
    y_pred = model(x, w1, w2, b)
    mse = np.mean((y_pred - y_true) ** 2)
    # Regularization
    # L1 L1 regularizer: penalty = abs(w1) + abs(w2) + abs(b)
    l1_regularizer = abs(w1) + abs(w2) + abs(b)
    l2_regularizer = w1 ** 2 + w2 + b
    return mse + l2_regularizer

In [33]:
mse = cost_function(X_train, y_train, w1, w2, b)
print(f"MSE is {mse:0.2f}  (Parameters not learned yet.)")

MSE is 3698524.98  (Parameters not learned yet.)

In [34]:

def compute_gradient(X, y_true, w1, w2, b):
    delta = 1e-9
    
    cost_1 = cost_function(X, y_true, w1, w2, b)
    cost_2 = cost_function(X, y_true, w1 + delta, w2, b)
    cost_3 = cost_function(X, y_true, w1, w2 + delta, b)
    cost_4 = cost_function(X, y_true, w1, w2, b + delta)
    
    dw1 = (cost_2 - cost_1) / delta
    dw2 = (cost_3 - cost_1) / delta
    db = (cost_4 - cost_1) / delta
    return dw1, dw2, db

In [35]:
""" Hyperparameters
Learning rate
Epoch
Batch size
Optimizer
Learning rate scheduler
"""

""" Train the model """

def train_model(train_X, train_y, val_X, val_y, epochs=100, lr=0.003):
    """ Initialize the parameters """
    w1 = 0
    w2 = 0
    b = 0
    
    for epoch in range(epochs):
        """ compute logits """
        loss = cost_function(train_X, train_y, w1, w2, b)
        val_loss = cost_function(val_X, val_y, w1, w2, b)
        
        """ compute gradient """
        dw1, dw2, db = compute_gradient(train_X, train_y, w1, w2, b)
        
        """ update parameters """
        w1 = w1 - lr * dw1
        w2 = w2 - lr * dw2
        b = b - lr * db
        
        if epoch % 100 == 0:
            print(f"Epoch {epoch} / {epochs} loss: {loss:.4f} val_loss: {val_loss:.4f}")
            
    return w1, w2, b
    
w1, w2, b = train_model(X_train, y_train, X_val, y_val)
train_loss = cost_function(X_train, y_train, w1, w2, b)
test_loss = cost_function(X_test, y_test, w1, w2, b)

Epoch 0 / 100 loss: 0.8954 val_loss: 0.8433

In [36]:
print(f"w1: {w1}, w2: {w2}, b: {b}, loss={train_loss:.4f}")
print(f"w1: {w1}, w2: {w2}, b: {b}, test_loss={test_loss:.4f}")

w1: 0.04227026928482758, w2: -0.18256085443368875, b: -0.2037006227029181, loss=0.6196
w1: 0.04227026928482758, w2: -0.18256085443368875, b: -0.2037006227029181, test_loss=1.2926

In [37]:
"""
Overfitting: When model performs well in training data but poorly on test data
Underfitting: When model performs poorly on train and test
Generalization: When model performs equally well in both train and test data
"""
print("Overfitting-Uderfitting-Generalization")

Overfitting-Uderfitting-Generalization

In [38]:
""" How to overcome overfitting
Checkpoint 1: Create a fairly balanced partition of the data 
              i.e. each partition (test, train, val contains all variation proportionately)
Checkpoint 2: Dataset is too simple to learn
Checkpoint 3: Model is too complex that can easily memorize the pattern in the training set
Checkpoint 4: Dropout (Deep Learning / ANN)
              Regularization (Add penalty parameter in the cost function)  
"""
print("Overcome overfitting")

Overcome overfitting